PackageIdentifier: Microsoft.AzureCLI
PackageVersion: 2.24.2
PackageName: Azure CLI
Publisher: Microsoft Corporation
Moniker: azure-cli
PackageUrl: https://docs.microsoft.com/en-us/cli/azure/
License: Copyright (C) Microsoft Corporation
ShortDescription: The Azure command-line interface (Azure CLI) is a set of commands used to create and manage Azure resources. The Azure CLI is available across Azure services and is designed to get you working quickly with Azure, with an emphasis on automation.
Installers:
- Architecture: x64
  InstallerUrl: https://azcliprod.azureedge.net/msi/azure-cli-2.24.2.msi
  InstallerType: msi
  InstallerSha256: 82c615d8799000020dedcf9029e5131c984c838741c27e38e6fe2af3513b4c73
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
